# Generated by Django 5.0 on 2025-11-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotSnapshot',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pilot_snapshot', serialize=False, to='waitlist.evecharacter')),
                ('skills_json', models.TextField(blank=True, help_text='JSON response from ESI /skills/ endpoint', null=True)),
                ('implants_json', models.TextField(blank=True, help_text='JSON response from ESI /implants/ endpoint', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
