# Generated by Django 5.0 on 2025-11-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_evegroup_evetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetype',
            name='slot',
            field=models.IntegerField(blank=True, help_text='Implant slot (if applicable)', null=True),
        ),
    ]
