# Generated by Django 5.0 on 2025-11-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_evetype_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetype',
            name='icon_url',
            field=models.CharField(blank=True, help_text="URL for the item's icon", max_length=255, null=True),
        ),
    ]
