# Generated by Django 5.0 on 2025-11-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_evetype_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='evegroup',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
