# Generated by Django 5.0 on 2025-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0005_evegroup_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetype',
            name='hi_slots',
            field=models.IntegerField(blank=True, help_text='Ship: High slots', null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='low_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Low slots', null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='med_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Medium slots', null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='rig_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Rig slots', null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='slot_type',
            field=models.CharField(blank=True, db_index=True, help_text="Module: 'high', 'mid', 'low', 'rig', 'subsystem', or 'drone'", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='subsystem_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Subsystem slots', null=True),
        ),
    ]
