# Generated by Django 5.0 on 2025-11-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetwaitlist',
            name='approved_fits',
        ),
        migrations.AddField(
            model_name='shipfit',
            name='fit_issues',
            field=models.TextField(blank=True, help_text='A list of issues found by the parser', null=True),
        ),
        migrations.AddField(
            model_name='shipfit',
            name='hull_fleet_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shipfit',
            name='ship_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipfit',
            name='tank_type',
            field=models.CharField(blank=True, help_text='e.g., Shield or Armor', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipfit',
            name='total_fleet_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shipfit',
            name='waitlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_fits', to='waitlist.fleetwaitlist'),
        ),
    ]
