# Generated by Django 5.0 on 2025-11-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_remove_fleetwaitlist_approved_fits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipfit',
            name='ship_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='fit_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='hull_fleet_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='ship_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='tank_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='total_fleet_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='waitlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_fits', to='waitlist.fleetwaitlist'),
        ),
    ]
