# Generated by Django 5.0 on 2025-11-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_shipfit_ship_type_id_alter_shipfit_fit_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipfit',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('DPS', 'DPS'), ('LOGI', 'Logi'), ('SNIPER', 'Sniper'), ('MAR_DPS', 'MAR DPS'), ('MAR_SNIPER', 'MAR Sniper')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fleetwaitlist',
            name='fleet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='waitlist', serialize=False, to='waitlist.fleet'),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='ship_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='waitlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_fits', to='waitlist.fleetwaitlist'),
        ),
    ]
