# Generated by Django 5.0 on 2025-11-07 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_evetype_icon_url'),
        ('waitlist', '0005_alter_fleet_description_alter_fleet_esi_fleet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipfit',
            name='parsed_fit_json',
            field=models.TextField(blank=True, help_text='JSON representation of the parsed fit, including item IDs and icon URLs', null=True),
        ),
        migrations.CreateModel(
            name='DoctrineFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Standard Vargur', 'Logi Basilisk'", max_length=255, unique=True)),
                ('category', models.CharField(choices=[('NONE', 'None'), ('DPS', 'DPS'), ('LOGI', 'Logi'), ('SNIPER', 'Sniper'), ('MAR_DPS', 'MAR DPS'), ('MAR_SNIPER', 'MAR Sniper')], db_index=True, default='NONE', max_length=20)),
                ('fit_items_json', models.TextField(help_text='JSON dictionary of {type_id: quantity} for all required items')),
                ('description', models.TextField(blank=True, null=True)),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctrine_fits', to='pilot.evetype')),
            ],
        ),
    ]
