# Generated by Django 5.0 on 2025-11-07 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_evetype_icon_url'),
        ('waitlist', '0006_shipfit_parsed_fit_json_doctrinefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinefit',
            name='fit_items_json',
            field=models.TextField(blank=True, help_text='JSON dictionary of {type_id: quantity} for all required items'),
        ),
        migrations.AlterField(
            model_name='doctrinefit',
            name='ship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctrine_fits', to='pilot.evetype'),
        ),
        migrations.CreateModel(
            name='FitSubstitutionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'T2 Large Shield Extenders', 'T2 Large Cap Batteries'", max_length=255, unique=True)),
                ('base_item', models.ForeignKey(help_text='The base item specified in a doctrine (e.g., Large Shield Extender II)', on_delete=django.db.models.deletion.CASCADE, related_name='substitution_base', to='pilot.evetype')),
                ('substitutes', models.ManyToManyField(blank=True, help_text="All other items that are considered 'equal or better' (e.g., Caldari Navy LSE)", related_name='allowed_as_substitute', to='pilot.evetype')),
            ],
        ),
    ]
