# Generated by Django 5.0 on 2025-11-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0009_fleetwing_fleetsquad'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinefit',
            name='parsed_fit_json',
            field=models.TextField(blank=True, help_text='JSON representation of the parsed fit (slotted).', null=True),
        ),
        migrations.AddField(
            model_name='doctrinefit',
            name='raw_fit_eft',
            field=models.TextField(blank=True, help_text='The raw EFT-formatted fit string.', null=True),
        ),
    ]
